version: '3.2'
# web container
services:
  repo:
    build: .
    container_name: tmax-b2b-repo
    image: tmax-b2b-repo
    ports:
      - "20080:80"
      - "20022:22"
    volumes:
      - type : "bind"
        source : "/var/spool/aptly"
        target : "/var/spool/aptly"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: tmax-b2b-ci
    user: root
    ports:
      - "29000:8080" # jenkins port
    volumes:
      - type : "bind"
        source : "${PWD}/jenkins"
        target : "/var/jenkins_home"
    links:
      - repo
